#! /bin/sh

sysctl -w net.ipv4.ip_forward=1 &>/dev/null

iptables -t nat -A POSTROUTING -o wlan1 -j MASQUERADE
#iptables -A FORWARD -i wlan1 -o wlan0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT 
#iptables -A FORWARD -i wlan0 -o wlan1 -j ACCEPT

iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i wlan0 -o wlan1 -j ACCEPT

#net.ipv4.ip_forward = 1
