#!/bin/bash

WLANPHY=wlan1
WLANPIDFILE=/var/run/udhcpc.$WLANPHY.pid

router=`ip route | grep $WLANPHY | awk '/default/ {print $3}'`
/bin/ping -q -c1 $router &> /dev/null

if [ $? -eq  0 ]
then
  true
else
  /bin/kill -9 `cat $WLANPIDFILE`
  udhcpc -R -n -p $WLANPIDFILE -i $WLANPHY
  echo "$WLANPHY reconnected at `date`"
fi
