#!/bin/sh
#
# Start psplash....
#

export DISPLAY=:0

case "$1" in
  start)
	echo "Starting psplash..."
	/usr/bin/X :0 &
	/bin/sleep 2
	/usr/bin/psplash &
	/bin/sleep 1
	/usr/bin/psplash-write "MSG Loading URUS OS..."
	/usr/bin/psplash-write "PROGRESS 10"
	/bin/sleep 1
	#/etc/init.d/network start
	/usr/bin/psplash-write "PROGRESS 50"
	/bin/login -f urusapp
	/usr/bin/psplash-write "PROGRESS 90"
	/bin/sleep 1
	#/usr/bin/psplash-write "MSG Init OK!"
	#/usr/bin/psplash &
	/usr/bin/xset -dpms
	/usr/bin/xset s noblank
	/usr/bin/xset s off
	/usr/bin/psplash-write "PROGRESS 100"
	/usr/bin/psplash-write "MSG Init OK!"
	/bin/sleep 1
	/usr/bin/psplash-write "QUIT"
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
