#!/bin/sh
#
# Start psplash....
#

export DISPLAY=:0
AMIXER="no"
ALSACTL="no"

if [ -e /usr/bin/amixer ] ; then
AMIXER="yes"
fi

if [ -e /usr/sbin/alsactl ] ; then
ALSACTL="yes"
fi

case "$1" in
  start)
    #clear
    echo 0 > /proc/sys/kernel/printk
	echo "Starting..."
	/usr/bin/X vt1 -noreset -s 0 -mouse mouse -keybd keyboard :0 &>/dev/null &
	/bin/sleep 3
	/usr/bin/psplash -n &
	/bin/sleep 1
	/usr/bin/psplash-write "MSG Loading URUS OS..."
	/usr/bin/psplash-write "PROGRESS 10"
	/bin/sleep 1
	#/etc/init.d/network start
	/usr/bin/psplash-write "PROGRESS 50"
	#mount /dev/mmcblk0p11 /mnt/disk1
	exec su urusapp -c /usr/bin/urusx &
	/usr/bin/psplash-write "PROGRESS 90"
	/bin/sleep 1
	#/usr/bin/psplash-write "MSG Init OK!"
	#/usr/bin/psplash &
	/usr/bin/xset -dpms
	/usr/bin/xset s noblank
	/usr/bin/xset s off
	/usr/bin/psplash-write "PROGRESS 100"
	/usr/bin/psplash-write "MSG Init OK!"
	/bin/sleep 1
    if [ "$ALSACTL" = "yes" ] ; then
        /usr/sbin/alsactl restore
    fi
	/usr/bin/psplash-write "QUIT"
	;;
  stop)
    if [ "$ALSACTL" = "yes" ] ; then
        /usr/sbin/alsactl store
    fi
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
